"""Named color schemes including Microsoft brand palette."""

SCHEMES = {
    "hero": {
        "id": "hero",
        "name": "Hero — Cyan + Gray",
        "colors": ["#00A4EF", "#737373"],
        "ratios": [0.60, 0.40],
        "background": "#EAEAEA",
    },
    "hero_transparent": {
        "id": "hero_transparent",
        "name": "Hero — Transparent",
        "colors": ["#00A4EF", "#737373"],
        "ratios": [0.60, 0.40],
        "background": None,
    },
    "dark": {
        "id": "dark",
        "name": "Dark — Cyan + White",
        "colors": ["#00A4EF", "#FFFFFF"],
        "ratios": [0.55, 0.45],
        "background": "#000000",
    },
    "dark_transparent": {
        "id": "dark_transparent",
        "name": "Dark — Transparent",
        "colors": ["#00A4EF", "#FFFFFF"],
        "ratios": [0.55, 0.45],
        "background": None,
    },
    "mono_cyan": {
        "id": "mono_cyan",
        "name": "Mono Cyan",
        "colors": ["#00A4EF"],
        "ratios": [1.0],
        "background": None,
    },
    "mono_gray": {
        "id": "mono_gray",
        "name": "Mono Gray",
        "colors": ["#737373"],
        "ratios": [1.0],
        "background": None,
    },
    "white_on_black": {
        "id": "white_on_black",
        "name": "White on Black",
        "colors": ["#FFFFFF"],
        "ratios": [1.0],
        "background": "#000000",
    },
    "black_on_white": {
        "id": "black_on_white",
        "name": "Black on White",
        "colors": ["#000000"],
        "ratios": [1.0],
        "background": "#FFFFFF",
    },
    "signal_graphite": {
        "id": "signal_graphite",
        "name": "Signal Blue + Graphite",
        "colors": ["#3498C8", "#707070"],
        "ratios": [0.60, 0.40],
        "background": "#F8F8F8",
    },
    "signal_mist": {
        "id": "signal_mist",
        "name": "Signal Blue + Mist",
        "colors": ["#3498C8", "#C8D8E8"],
        "ratios": [0.55, 0.45],
        "background": "#F8F8F8",
    },
    "signal_fog": {
        "id": "signal_fog",
        "name": "Signal Blue + Fog",
        "colors": ["#3498C8", "#D0D0D0"],
        "ratios": [0.60, 0.40],
        "background": "#F8F8F8",
    },
    "graphite_fog": {
        "id": "graphite_fog",
        "name": "Graphite + Fog",
        "colors": ["#707070", "#D0D0D0"],
        "ratios": [0.55, 0.45],
        "background": "#F8F8F8",
    },
    "signal_blue_mono": {
        "id": "signal_blue_mono",
        "name": "Signal Blue Mono",
        "colors": ["#3498C8"],
        "ratios": [1.0],
        "background": "#F8F8F8",
    },
    "sunset": {
        "id": "sunset",
        "name": "Sunset — Amber + Blaze",
        "colors": ["#FCAD36", "#F35726"],
        "ratios": [0.55, 0.45],
        "background": "#FDE4C8",
    },
    "sunset_warm": {
        "id": "sunset_warm",
        "name": "Sunset — Orange + Coral + Orchid",
        "colors": ["#F76A32", "#ED7364", "#EC8AC5"],
        "ratios": [0.45, 0.30, 0.25],
        "background": "#FDE4C8",
    },
    "sunset_dusk": {
        "id": "sunset_dusk",
        "name": "Sunset — Ember + Blaze + Magenta",
        "colors": ["#4E1A0A", "#F35726", "#EEB4E7"],
        "ratios": [0.35, 0.40, 0.25],
        "background": "#1a0a05",
    },
    "sunset_pastel": {
        "id": "sunset_pastel",
        "name": "Sunset — Peach + Salmon + Blush",
        "colors": ["#FDE4C8", "#F1785B", "#F5D0E8"],
        "ratios": [0.35, 0.40, 0.25],
        "background": "#8E3214",
    },
    "sunset_transparent": {
        "id": "sunset_transparent",
        "name": "Sunset — Transparent",
        "colors": ["#FCAD36", "#F35726", "#EC8AC5"],
        "ratios": [0.40, 0.35, 0.25],
        "background": None,
    },
}
